# This is a workflow to update the README.md automatically 

name: Update README.md

# Controls when the workflow will run
on:
  # Triggers the workflow when an issue is opened
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: github_context_step

      # Run update_readme.py
      - name: Run update_readme.py
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          python update_readme.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Commit and push updated README.md file
      - name: Commit changes
        run: |
          git config --global user.name 'younnggsuk'
          git config --global user.email 'younnggsuk@gmail.com'
          git add -A
          git commit -m "Update README.md"
      - name: Push changes
        run: |
          git push
